// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RepoPostgrSQL.Data;

namespace RepoPostgrSQL.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.27")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("RepoPostgrSQL.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<float>("CostDetails")
                        .HasColumnType("real");

                    b.Property<byte>("ForByte")
                        .HasColumnType("smallint");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.Property<int[]>("arr")
                        .HasColumnType("integer[]");

                    b.Property<double[,]>("arr3")
                        .HasColumnType("double precision[]");

                    b.Property<double>("cost")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("dateTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<decimal>("decimalType")
                        .HasColumnType("numeric");

                    b.Property<bool>("isused")
                        .HasColumnType("boolean");

                    b.Property<long>("longtype")
                        .HasColumnType("bigint");

                    b.Property<char>("symbol")
                        .HasColumnType("character(1)");

                    b.Property<long>("uinttype")
                        .HasColumnType("bigint");

                    b.Property<decimal>("ulongtype")
                        .HasColumnType("numeric(20,0)");

                    b.HasKey("Id");

                    b.ToTable("products");
                });
#pragma warning restore 612, 618
        }
    }
}
